// <auto-generated />
using System;
using AdminDashboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminDashboard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619101514_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminDashboard.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceT")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_t");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_email");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a987db56-f99f-47f5-93a8-1ba71889df80"),
                            BalanceT = 100m,
                            Email = "john@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("57dc4274-2d41-4e65-b11a-4a2c623bb812"),
                            BalanceT = 200m,
                            Email = "jane@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = new Guid("3b30c2c0-294b-4d96-8026-5cdc0403e139"),
                            BalanceT = 300m,
                            Email = "bob@example.com",
                            Name = "Bob Johnson"
                        });
                });

            modelBuilder.Entity("AdminDashboard.Domain.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rates");

                    b.ToTable("exchange_rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad087526-b475-4a42-86c0-be2766964078"),
                            LastUpdated = new DateTime(2025, 6, 19, 10, 15, 14, 44, DateTimeKind.Utc).AddTicks(5620),
                            Rate = 10.0m
                        });
                });

            modelBuilder.Entity("AdminDashboard.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payments_client_id");

                    b.ToTable("payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b28090be-0fc5-4c96-80c6-fe182eb2ca79"),
                            Amount = 50m,
                            ClientId = new Guid("a987db56-f99f-47f5-93a8-1ba71889df80"),
                            Date = new DateTime(2025, 6, 19, 10, 15, 14, 311, DateTimeKind.Utc).AddTicks(4865),
                            Description = "Payment 1"
                        },
                        new
                        {
                            Id = new Guid("60f8806a-b080-4895-a587-3505112e8993"),
                            Amount = 75m,
                            ClientId = new Guid("a987db56-f99f-47f5-93a8-1ba71889df80"),
                            Date = new DateTime(2025, 6, 19, 10, 15, 14, 311, DateTimeKind.Utc).AddTicks(5105),
                            Description = "Payment 2"
                        },
                        new
                        {
                            Id = new Guid("9a68f8ef-faae-4d12-b05a-e297721682c9"),
                            Amount = 100m,
                            ClientId = new Guid("57dc4274-2d41-4e65-b11a-4a2c623bb812"),
                            Date = new DateTime(2025, 6, 19, 10, 15, 14, 311, DateTimeKind.Utc).AddTicks(5110),
                            Description = "Payment 3"
                        },
                        new
                        {
                            Id = new Guid("49d13a3b-6192-43ca-b28c-61b5d7394062"),
                            Amount = 25m,
                            ClientId = new Guid("3b30c2c0-294b-4d96-8026-5cdc0403e139"),
                            Date = new DateTime(2025, 6, 19, 10, 15, 14, 311, DateTimeKind.Utc).AddTicks(5114),
                            Description = "Payment 4"
                        },
                        new
                        {
                            Id = new Guid("ec3b9d7f-03c9-406d-bb74-bfd24702bd4d"),
                            Amount = 150m,
                            ClientId = new Guid("3b30c2c0-294b-4d96-8026-5cdc0403e139"),
                            Date = new DateTime(2025, 6, 19, 10, 15, 14, 311, DateTimeKind.Utc).AddTicks(5119),
                            Description = "Payment 5"
                        });
                });

            modelBuilder.Entity("AdminDashboard.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AdminDashboard.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1483cc99-29ad-42f4-9528-1df013131c65"),
                            Color = "#ff0000",
                            Name = "VIP"
                        },
                        new
                        {
                            Id = new Guid("60646b56-eac8-4297-8b88-949a6f5f684c"),
                            Color = "#00ff00",
                            Name = "Regular"
                        });
                });

            modelBuilder.Entity("AdminDashboard.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8a1d99f-5b86-4aad-9eae-8ca0244682ff"),
                            Email = "admin@mirra.dev",
                            PasswordHash = "$2a$11$S/dVHGgcEwp9ChhFaxbjgOc15VKnLsxa/Qzbm40oOfSimHINBI9aC"
                        });
                });

            modelBuilder.Entity("ClientTag", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uuid")
                        .HasColumnName("clients_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("ClientsId", "TagsId")
                        .HasName("pk_client_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_client_tag_tags_id");

                    b.ToTable("client_tag", (string)null);

                    b.HasData(
                        new
                        {
                            ClientsId = new Guid("a987db56-f99f-47f5-93a8-1ba71889df80"),
                            TagsId = new Guid("1483cc99-29ad-42f4-9528-1df013131c65")
                        },
                        new
                        {
                            ClientsId = new Guid("57dc4274-2d41-4e65-b11a-4a2c623bb812"),
                            TagsId = new Guid("1483cc99-29ad-42f4-9528-1df013131c65")
                        },
                        new
                        {
                            ClientsId = new Guid("3b30c2c0-294b-4d96-8026-5cdc0403e139"),
                            TagsId = new Guid("60646b56-eac8-4297-8b88-949a6f5f684c")
                        });
                });

            modelBuilder.Entity("AdminDashboard.Domain.Payment", b =>
                {
                    b.HasOne("AdminDashboard.Domain.Client", null)
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_clients_client_id");
                });

            modelBuilder.Entity("AdminDashboard.Domain.RefreshToken", b =>
                {
                    b.HasOne("AdminDashboard.Domain.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("ClientTag", b =>
                {
                    b.HasOne("AdminDashboard.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_tag_clients_clients_id");

                    b.HasOne("AdminDashboard.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_tag_tags_tags_id");
                });

            modelBuilder.Entity("AdminDashboard.Domain.Client", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AdminDashboard.Domain.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
