services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      # Only for development purposes, use .env file instead
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=admin-dashboard
    ports:
      - "5432:5432"
    volumes:
      - admin-dashboard-data:/var/lib/postgresql/data
  backend:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Only for development purposes, use .env file instead
      - ConnectionStrings__PostgresConnection=Server=postgres-db:5432;User Id=postgres;Password=password;Database=admin-dashboard
    build:
      context: .
      dockerfile: ./src/AdminDashboard.Api/Dockerfile
    image: backend
    container_name: admin-dashboard-backend
    ports:
      - "5000:80"
    depends_on:
      - postgres-db
  frontend:
    restart: on-failure
    build:
      context: ./src/AdminDashboard.WebApp
      dockerfile: Dockerfile
    image: frontend
    container_name: admin-dashboard-frontend
    ports:
      - "5173:80"

volumes:
  admin-dashboard-data: